[package]
name = "gnostique"
version = "0.1.0-alpha.2"
edition = "2021"
license = "Apache-2.0 OR MIT"
repository = "https://jirijakes.com/code/gnostique"
description = "Native desktop Nostr client."
keywords = ["nostr", "client", "GTK", "GUI"]
exclude = ["doc/"]

[dependencies]
chrono = "0.4.23"
directories = "4.0.1"
futures-util = "0.3.25"
gtk = { package = "gtk4", version = "0.5.5", features = ["v4_6"] }
linkify = "0.9.0"
nostr-sdk = "0.15.0"
once_cell = "1.17.0"
relm4 = "0.5.0-rc.1"
reqwest = { version = "0.11.14", features = ["stream"] }
serde_json = "1.0.91"
tokio = { version = "1.24.2", features = ["full"] }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
