[package]
name = "gnostique"
version = "0.1.0-alpha.2"
edition = "2021"
license = "Apache-2.0 OR MIT"
repository = "https://jirijakes.com/code/gnostique"
description = "Native desktop Nostr client."
keywords = ["nostr", "client", "GTK", "GUI"]
exclude = ["doc/"]

[dependencies]
chrono = "0.4.23"
directories = "4.0.1"
futures-util = "0.3.26"
gtk = { package = "gtk4", version = "0.5.5", features = ["v4_8"] }
html-escape = "0.2.13"
linkify = "0.9.0"
nostr-sdk = { git = "https://github.com/jirijakes/nostr", branch="event_id_hash" }
once_cell = "1.17.0"
regex = "1.7.1"
relm4 = { git = "https://github.com/Relm4/Relm4" }
reqwest = { version = "0.11.14", features = ["stream"] }
serde_json = "1.0.91"
sqlx = { version = "0.6.2", features = ["sqlite", "runtime-tokio-native-tls", "chrono", "offline"] }
tokio = { version = "1.25.0" }
tracing = "0.1.37"
tracing-subscriber = { version = "0.3.16", features = ["env-filter"] }
